url: "http://voletiv.github.io/timeline"
baseurl: ""

# Site Settings
title: Vikram Voleti
email: vikram.voleti@gmail.com
github_username:  voletiv
github_site: "github.com/voletiv"
linkedIn_site: "https://in.linkedin.com/in/vikram-voleti-45372222"
description: "My technical diary."
twitter_username: vikky2904
keywords: "blog, academic, Vikram, Voleti"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/GOR.png"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
