url: "http://voletiv.github.io"
baseurl: ""

# Site Settings
title: Vikram Voleti
email: vikram.voleti@gmail.com
description: "My technical diary."
twitter_username: vikky2904
keywords: "blog, academic, Vikram, Voleti"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
