title: Vikram Voleti
author: Vikram Voleti
url: "voletiv.github.io"
baseurl: ""

description: Vikram Voleti's website

markdown: kramdown

google_analytics_tracking_id: UA-109052064-1

sass:
    style: compressed
    sass_dir: _sass

